raise:
  name: Raise
  description: Start increasing Hue brightness.
  target:
    entity:
      domain: light
  fields:
    sweep_time:
      name: Sweep time
      description: Duration of a full 100-0% sweep.
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: s
    limit:
      name: Maximum brightness limit
      description: Default 100%
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

lower:
  name: Lower
  description: Start decreasing Hue brightness.
  target:
    entity:
      domain: light
  fields:
    sweep_time:
      name: Sweep time
      description: Duration of a full 0-100% sweep.
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: s
    limit:
      name: Minimum brightness limit
      description: Default 0% (turns off). Choose 0.2%+ to keep a light turned on (2.0%+ for Hue Essential).
      selector:
        number:
          min: 0
          max: 99
          unit_of_measurement: "%"

stop:
  name: Stop
  description: Stop an active transition.
  target:
    entity:
      domain: light
