raise:
  name: Raise
  description: Start increasing the brightness.
  target:
    entity:
      domain: light
  fields:
    sweep_time:
      name: Sweep Time
      description: Duration of a full 100-0% transition.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: s
    limit:
      name: Target Brightness
      description: Default is 100%.
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

lower:
  name: Lower
  description: Start decreasing the brightness and turn off at 0%. 
  target:
    entity:
      domain: light
  fields:
    sweep_time:
      name: Sweep Time
      description: Duration of a full 0-100% transition.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: s
    limit:
      name: Target Brightness
      description: Default is 0%. Use 0.2% to keep a Hue light on.
      selector:
        number:
          min: 0
          max: 99
          unit_of_measurement: "%"

stop:
  name: Stop
  description: Stop a brightness transition.
  target:
    entity:
      domain: light