raise:
  name: Raise
  description: Start raising Hue brightness.
  target:
    entity:
      domain: light
  fields:
    sweep_time:
      name: Sweep
      description: Duration of 0-100% sweep.
      default: 5
      required: false
      selector:
        number:
          min: 0.1
          step: any
          unit_of_measurement: s
          mode: box
    limit:
      name: Maximum brightness limit
      description: Stop transition at limit.
      default: 100
      required: false
      selector:
        number:
          min: 0.2
          max: 100
          step: 0.2
          unit_of_measurement: "%"

lower:
  name: Lower
  description: Start lowering Hue brightness.
  target:
    entity:
      domain: light
  fields:
    sweep_time:
      name: Sweep
      description: Duration of 100-0% sweep.
      default: 5
      required: false
      selector:
        number:
          min: 0.1
          step: any
          unit_of_measurement: s
          mode: box
    limit:
      name: Minimum brightness limit
      description: Light turns off at 0%. Choose 0.2%+ to keep standard Hue lights turned on, and 2%+ for Essential series.
      default: 0.2
      required: false
      selector:
        number:
          min: 0
          max: 99.8
          step: 0.2
          unit_of_measurement: "%"

stop:
  name: Stop
  description: Stop a brightness transition.
  target:
    entity:
      domain: light
